language: node_js
node_js:
  - "6"
before_install:
  - git config --global push.default matching
  - git config --global user.name "erguotou"
  - git config --global user.email "erguotou525@gmail.com"
install:
  - npm install
script:
  - npm run demo:build
  - cd demo/dist
  - git init
  - git add -A
  - git commit -m "Auto commit"
  - git push -u https://$GH_TOKEN@github.com/erguotou520/weex-uikit.git HEAD:gh-pages --force
cache:
  directories:
    - node_modules
